export const GET_USER_INFO = "AUTH/GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "AUTH/GET_USER_INFO_SUCCESS";

export const CHANGE_LOGIN_INFO = "AUTH/CHANGE_LOGIN_INFO";
export const CHANGE_REGISTER_INFO = "AUTH/CHANGE_REGISTER_INFO";

export const LOGIN = "AUTH/LOGIN";
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGIN_ERROR = "AUTH/LOGIN_ERROR";

export const REGISTER = "AUTH/REGISTER";
export const REGISTER_SUCCESS = "AUTH/REGISTER_SUCCESS";
export const REGISTER_ERROR = "AUTH/REGISTER_ERROR";

export const UPDATE_USER_INFO = "AUTH/UPDATE_USER_INFO";
export const UPDATE_USER_INFO_SUCCESS = "AUTH/UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_ERROR = "AUTH/UPDATE_USER_INFO_ERROR";

export const UPDATE_PASSWORD = "AUTH/UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "AUTH/UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "AUTH/UPDATE_PASSWORD_ERROR";

export const LOGOUT = "AUTH/LOGOUT";
