export const OPEN_CART_MENU = "CART/OPEN_CART_MENU";
export const TOGGLE_CART_MENU = "CART/TOGGLE_CART_MENU";
export const ADD_PRODUCT = "CART/ADD_PRODUCT";
export const REMOVE_PRODUCT = "CART/REMOVE_PRODUCT";
