export const GET_CATEGORIES = "CATEGORIES/GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "CATEGORIES/GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "CATEGORIES/GET_CATEGORIES_ERROR";
