export const GET_UPCOMMING_EVENTS = "EVENTS/GET_UPCOMMING_EVENTS";
export const GET_UPCOMMING_EVENTS_SUCCESS =
  "EVENTS/GET_UPCOMMING_EVENTS_SUCCESS";
export const GET_UPCOMMING_EVENTS_ERROR = "EVENTS/GET_UPCOMMING_EVENTS_ERROR";

export const GET_OCCURRED_EVENTS = "EVENTS/GET_OCCURRED_EVENTS";
export const GET_OCCURRED_EVENTS_SUCCESS = "EVENTS/GET_OCCURRED_EVENTS_SUCCESS";
export const GET_OCCURRED_EVENTS_ERROR = "EVENTS/GET_OCCURRED_EVENTS_ERROR";

export const RESET_STATE = "EVENTS/RESET_STATE";
