export const GET_EVENT = "EVENT/GET_EVENT";
export const GET_EVENT_SUCCESS = "EVENT/GET_EVENT_SUCCESS";
export const GET_EVENT_ERROR = "EVENT/GET_EVENT_ERROR";

export const JOIN_EVENT = "EVENT/JOIN_EVENT";
export const JOIN_EVENT_SUCCESS = "EVENT/JOIN_EVENT_SUCCESS";
export const JOIN_EVENT_ERROR = "EVENT/JOIN_EVENT_ERROR";

export const RESET_STATE = "EVENT/RESET_STATE";
