export const GET_FEEDBACK = "FEEDBACK/GET_FEEDBACK";
export const GET_FEEDBACK_SUCCESS = "FEEDBACK/GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_ERROR = "FEEDBACK/GET_FEEDBACK_ERROR";

export const SEND_FEEDBACK = "FEEDBACK/SEND_FEEDBACK";
export const SEND_FEEDBACK_SUCCESS = "FEEDBACK/SEND_FEEDBACK_SUCCESS";
export const SEND_FEEDBACK_ERROR = "FEEDBACK/SEND_FEEDBACK_ERROR";

export const RESET_STATE = "FEEDBACK/RESET_STATE";
