export const FORGOT_PASSWORD = "FORGOT_PASSWORD/FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS =
  "FORGOT_PASSWORD/FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD/FORGOT_PASSWORD_ERROR";

export const FORGOT_PASSWORD_CONFIRMATION =
  "FORGOT_PASSWORD/FORGOT_PASSWORD_CONFIRMATION";
export const FORGOT_PASSWORD_CONFIRMATION_SUCCESS =
  "FORGOT_PASSWORD/FORGOT_PASSWORD_CONFIRMATION_SUCCESS";
export const FORGOT_PASSWORD_CONFIRMATION_ERROR =
  "FORGOT_PASSWORD/FORGOT_PASSWORD_CONFIRMATION_ERROR";

export const RESET_STATE = "FORGOT_PASSWORD/RESET_STATE";
