export const CREATE_ORDER = "ORDER/CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "ORDER/CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "ORDER/CREATE_ORDER_ERROR";

export const GET_ORDER_HISTORY = "ORDER/GET_ORDER_HISTORY";
export const GET_ORDER_HISTORY_SUCCESS = "ORDER/GET_ORDER_HISTORY_SUCCESS";
export const GET_ORDER_HISTORY_ERROR = "ORDER/GET_ORDER_HISTORY_ERROR";

export const GET_ORDER_DETAIL = "ORDER/GET_ORDER_DETAIL";
export const GET_ORDER_DETAIL_SUCCESS = "ORDER/GET_ORDER_DETAIL_SUCCESS";
export const GET_ORDER_DETAIL_ERROR = "ORDER/GET_ORDER_DETAIL_ERROR";

export const REDEEM_VOUCHER = "ORDER/REDEEM_VOUCHER";
export const REDEEM_VOUCHER_SUCCESS = "ORDER/REDEEM_VOUCHER_SUCCESS";
export const REDEEM_VOUCHER_ERROR = "ORDER/REDEEM_VOUCHER_ERROR";
