export const GET_PRODUCTS = "PRODUCTS/GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "PRODUCTS/GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "PRODUCTS/GET_PRODUCTS_ERROR";

export const CHANGE_FILTER = "PRODUCTS/CHANGE_FILTER";
export const RESET_STATE = "PRODUCTS/RESET_STATE";
