export const GET_PRODUCT = "PRODUCT/GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "PRODUCT/GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "PRODUCT/GET_PRODUCT_ERROR";

export const RESET_STATE = "PRODUCT/RESET_STATE";
