export const GET_PRODUCTS_SALE = "SALES/GET_PRODUCTS_SALE";
export const GET_PRODUCTS_SALE_SUCCESS = "SALES/GET_PRODUCTS_SALE_SUCCESS";
export const GET_PRODUCTS_SALE_ERROR = "SALES/GET_PRODUCTS_SALE_ERROR";

export const RESET_STATE = "SALES/RESET_STATE";
