export const GET_VIDEOS = "VIDEOS/GET_VIDEOS";
export const GET_VIDEOS_SUCCESS = "VIDEOS/GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_ERROR = "VIDEOS/GET_VIDEOS_ERROR";

export const RESET_STATE = "VIDEOS/RESET_STATE";
